# look at learner/Config.java for more details

learning:
    sutinfoFile: "sutinfo.yaml"
    #maximum time of learning in seconds allowed (0 means disabled)
    maxTime: 0
    
testing:
    seed: 1299777356020
    minTraceLength: 100
    maxTraceLength: 150
    # if we use maxTime learning above then we can use 'infinite' number test traces
    maxNumTraces: 1000      
    
learnResults:
  outputDir: "output/${sutname}"

sutInterface:
   # flatten alphabet for SUT with actions with params : 
   #  * if min=max then flattening is disabled 
   #  * flatten actions to just simple strings by concatenating param values to action string name
   #    because we enumerate over param values each action gives multiple flattened actions
   #    the range we enumerate over is limited by a min and max value
   flattenAlphabet:
      minValue: 0
      maxValue: 1

logging:
    # configure outputting of log messages         
    logFile: "log.txt"
    logFileThreshold: "debug"
    consoleThreshold: "info"
    # configure which logging messages are generated 
    rootLoggerLevel: "OFF" 
    childLoggerLevels : {
        ## you can specify per class which logging message of which level are enabled 
        #abslearning.learner: "debug",
        abslearning.learner.Main: info,
        #abslearning.learner.Statistics: info,
    }
    
    # you can add extra log4j properties
    # IMPORTANT: the keyword "off" must be between quotes otherwise it will be interpreted by yaml as boolean false!
    #log4jExtraProperties : { log4j.threshold: "off" } # example disabling all log4j logging

    # configure special logs
    special: 
        hypotheses: false
        memQueries: true
        memQueriesFile : "memQueries.txt"  
        equivQueries: true
        equivQueriesFile : "equivQueries.txt"         
                                  
        

    
    
