learningParams:
    seed: 1299777356020
    minValue: 0
    maxValue: 300
    minTraceLength: 8
    maxTraceLength: 8
    maxNumTraces: 500
    sutInterface: sutinfo.yaml
    mapper: CLIENT_NO_ACTIONS_ALL_V
tcpParams:
    sutPort: 18200
    sutIP: 127.0.0.1
    oracle: client


